name: Josh's Courier GitHub Action
description: Send e-mail, sms, push, etc. notifications with Courier.
outputs:
  messageId:
    description: The Courier messageId
runs:
  using: node12
  main: dist/index.js
branding:
  color: purple
  icon: message-square
